### ISSUE TITLE
Validation and design changes for mobile number is not present in Check-in form

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#101]
### Summary:
Previously implemented validation checks for mobile number (length, starting number) is absent from this form; the change from contact number to mobile number and the placeholder text is also missing

### Steps to Reproduce:
- Proceed to Check-in form
- Enter 123 for Mobile Number
- Click Check-in

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/132490451-6ea5ecd9-24a6-4757-b80c-dea43b2d5899.png)

### Expected Results:
- Error Message

### Actual Results:
- Invalid input is accepted

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
The validation is present. However, the error field for displaying the error is missing.

**Comment by sophia-vista** [comment]
Ah mbmb. @ThisIsGrass
