### ISSUE TITLE
Current time does not match the actual current time after N minutes have passed

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#102]
### Summary
- Current time does not get updated unless the page is refreshed

### Steps to Reproduce:
1. Go to room management
2. Wait N minutes

### Expected Results:
- Current time should be able to change to match the actual current time after N minutes have passed without refreshing the page.

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/132494521-1d8a7b97-3bf7-4c15-8e99-84c0f736fc6a.png)

### Actual Results:
- The page needs to be refreshed in order for current time to display the actual current time after N minutes have passed

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
The time field in the room management screen is now editable as the employee may want to check in a guest earlier than the standard check in time of 2pm.
