### ISSUE TITLE
Today button in Room Management tab should not redirect to Calendar tab

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#103]
### Summary:
- Today button (button that displays current date) in Room Management tab should not redirect to Calendar tab

### Current Design:
![image](https://user-images.githubusercontent.com/75743382/132494260-627e7992-3d8e-4a03-8876-bc2d1ccb267f.png)

### Suggested Design:
Button could be disabled or have no onClickListener

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Removed redirect in the today button
