### ISSUE TITLE
Unavailable rooms in room management are colored white instead of gray

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#104]
### Summary
- Unavailable rooms does not adhere to the color as specified by the Legend

### Steps to Reproduce
1. check in for room 302

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/132658386-2dc3ae67-d3df-4bc4-85b4-901d10f8b797.png)

### Expected Results:
- Unavailable rooms should be colored gray

### Actual Results:
- Unavailable rooms are colored white

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ThisIsGrass** [comment]
Hello! Up with regards to the fix commit referencing this 4 days ago
