### ISSUE TITLE
Room booked is listed as Vacant in Booking Page after check-in

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#105]
### Summary:
- After checking in an existing booking, the room is listed as vacant on the booking page

### Steps to Reproduce:
1. Create a booking (Sept 9-10, Room 506)
2. Check in the created booking
3. Return to booking page for Sept 9

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/132659487-acb66005-955e-4e89-8ae0-51b777eb5882.png)
![image](https://user-images.githubusercontent.com/75743382/132659527-4a9934a0-d026-449b-95db-54d4576075c7.png)
![image](https://user-images.githubusercontent.com/75743382/132660386-8c0c2421-fa69-474d-a647-fc4f07cea481.png)
![image](https://user-images.githubusercontent.com/75743382/132659669-b85f26bc-d794-456c-adee-f4e2b8592cca.png)

### Expected Results:
- Room 506 is occupied
### Actual Results:
- Room 506 is vacant

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed. The room tile in the initial implementation is only marked as checked in after one minute.
