### ISSUE TITLE
"Number of PWD and Senior Citizens cannot exceed the Number of Guests" error should be displayed immediately

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#106]
### Summary
- "Number of PWD and Senior Citizens cannot exceed the Number of Guests" error should be displayed before confirming the booking to avoid confusing results on screen.

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/132664894-83c7cd64-5de5-45ba-8f12-6593e33b0dc1.png)

### Suggested Results:
- The error message should be displayed before pressing the confirm button

### Actual Results:
- The error message is displayed only after clicking the confirm button

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
This is possible. However, for the sake of consistency wouldn't it be better if the checking of "Number of PWD and Senior Citizens cannot exceed the Number of Guests" is displayed AFTER confirming the booking. Or an alternative would be to check everything in realtime.

**Comment by Zet-Warden** [comment]
If hindi hassle, I think better yung realtime, siguro when the user focuses out of the field saka ivavalidate? Otherwise, we can change where the validation happens, wherein fields get validated upon pressing reserve, book, etc. button instead of the confirm.
