### ISSUE TITLE
Max number of pax is incorrect for some rooms

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#107]
### Summary:
The maximum number of pax (which is dependent on the room type and the length of stay) is incorrect for some rooms (including Twin Bed, Combined Room, Triplex w/ Balcony, Two Bedroom) which causes errors in computing for the discount (#96) and extra charges.

### Steps to Reproduce:
- Create a booking (Room 302/303, Sept 9-10, 6 pax)

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/132665925-c403ce78-14f8-4e87-b737-d47682dfbd98.png)
![image](https://user-images.githubusercontent.com/75743382/132665528-cc1d93e7-6b0a-4a29-b9b0-16ca664c43f7.png)

### Expected Results:
- P800 extra charge

### Actual Results:
- No extra charges

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed. This is an issue with the encoding of room information to the database @ilearnonthisaccount
