### ISSUE TITLE
Validation should be done before displaying the modal

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#109]
### Summary
- Validation of input fields should be done before displaying the model.
- This should be for related form in all User Stories

### Suggested Results:
- Input fields must be validate before displaying the modal.

### Actual Results:
- Input fields are only validated once the 'confirm' button of the modal has been pressed.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 | #

**Comment by JanjanC** [comment]
Implemented starting from US5
