### ISSUE TITLE
Window should maximize on application start

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#11]
### Summary:
- Window is not maximized when the application starts

### Steps to Reproduce:
1. Run `npm start` on the console

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/129746351-014a6560-4a0f-40b3-a24c-a674a47a60f5.png)

### Expected Results:
- Window is maximized

### Actual Results:
- Window is unmaximized

| Additional Information | |
| ----------- | ----------- |
| Defect ID | 15-0009 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
