### ISSUE TITLE
End Date can be initialized to same date as Start Date

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#110]
### Summary:
In create forms (Reservation, Booking, Check-In), the end date can be set as the start date instead of the current date today. 

Ex. Booking is created for Jan 1 2022, both Start and End Date should show Jan 1, 2022

### Current Design:
![image](https://user-images.githubusercontent.com/75743382/132672895-693999b6-b804-4700-82c4-3ed0b75bf1f9.png)

### Suggested Design:
Set End Date to Start Date

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Would this not potentially cause some issues in the event that the user forgot to add an end date? This may result in scenarios wherein the data that is saved to the system is different from the intended data. In such scenarios, the user may not immediately notice that the end date is incorrect. In addition, reservation and booking does not allow creation of reservations/bookings that have the same start and end date.

**Comment by sophia-vista** [comment]
Question: Is the date picker automatically set to today? Or can it be manually set?

Best solution is that the text entry is blank but the date picker itself is set to the same date as the start date. What I proposed was an easy alternative if this is not possible; start date is same as end date so there is less navigation needed if booking is far into the future, AND so if the user forgets to set the end date, it will be flagged as incorrect (although in hindsight, this is still a problem for check-ins). 

I'm open to any other solutions naman!

**Comment by JanjanC** [comment]
To clarify lang, is the end date for some forms automatically initialized to today?

**Comment by sophia-vista** [comment]
The text field for the end date is blank, but the date picker is initialized to today

Create Reservation
![image](https://user-images.githubusercontent.com/75743382/133089308-4cf8ecf8-8746-49c3-9006-33a9baafa97c.png)

Create Booking
![image](https://user-images.githubusercontent.com/75743382/133089345-57e7a2d9-1434-49c8-b4f4-90c0d20acfc2.png)

Check-In
![image](https://user-images.githubusercontent.com/75743382/133089460-20799484-fa2c-4c5f-a3e3-cbfcd38c640e.png)

**Comment by JanjanC** [comment]
> Question: Is the date picker automatically set to today? Or can it be manually set?

It seems that the date picker is set to today by default.

>Although in hindsight, this is still a problem for check-ins

The start date for check-in is always the same date as today. Perhaps the end date for check-in may be left blank while the end dates for the reservation and booking are set to the same date as the start date. After all, reservation and booking does not allow creation of reservations/bookings that have the same start and end date. Hence, an error will still appear indicating that the end date cannot be the same as the start date.

**Comment by sophia-vista** [comment]
> Perhaps the end date for check-in may be left blank while the end dates for the reservation and booking are set to the same date as the start date.

Okok, sounds good!

**Comment by JanjanC** [comment]
Updated
