### ISSUE TITLE
JavaScript error occurs when checking-in reserved guest

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#111]
### Summary
- JavaScript error occurs when checking-in reserved guest

### Steps to Reproduce
1. create a reservation
2. check-in the newly made reservation

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/132676493-8b5bce33-667f-4bbb-995c-773e7fb193b7.png)

### Expected Results:
- check in pushes through

### Actual Results:
- JavaScript error occurs

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
FIxed
