### ISSUE TITLE
Incorrect extra person charge for monthly -- room 310 (Twin Bed with Balcony)

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#115]
### Summary
- Extra person charge is added when the number of pax inputted is 3 for Twin Bed with Balcony.
- Number of pax of 3 is only considered an extra person for non-monthly stays

### Steps to Reproduce
1. book room 310 for 30 days
2. input 3 for the number of pax

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/132982274-50746f5f-ae3d-4a24-bd6b-08dd8194187e.png)
![image](https://user-images.githubusercontent.com/74450482/132982329-b645af5e-e562-4a89-ace0-03fb8511c1e6.png)

### Expected Results:
- Total Cost should be 32400

### Actual Results:
- Total Cost is 32800

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by Zet-Warden** [comment]
update: same behavior for room 309 (Two Bedroom)

**Comment by Zet-Warden** [comment]
update: same behavior for room 302303(Combined Room)

**Comment by JanjanC** [comment]
Updated the computation such that the extra charges for monthly booking is different from the extra charges for daily/weekly booking.
