### ISSUE TITLE
App title in title bar should remain constant

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#116]
### Summary
- Since the application would be packaged as a desktop application, it would be better if the title in the title bar would remain the same despite moving through different "pages".

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/132982795-afc1c97f-1393-4f0d-9f98-43529645a113.png)
![image](https://user-images.githubusercontent.com/74450482/132982770-7198f4a0-d43b-4323-972c-e6187847ff55.png)

### Suggested Results:
- Suggested title is "Jaelle Residences" or "Jaelle Residences Management System"

### Actual Results:
- Title changes depending on the current "page" of the user

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ThisIsGrass** [comment]
Hello issue fixed!
