### ISSUE TITLE
Cannot check-in same day bookings

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#117]
### Summary:
Same day bookings should be accepted.

For check-ins:
- If it is currently before 4AM (12:00AM to 3:59AM), this counts as a 1-day booking (they have to check-out by 12NN today).
- Otherwise (on or after 4AM), this is considered as an early check-in (they can checkout tomorrow 12NN).

For check-outs:
- If it is currently before 6PM (12:01PM to 5:59PM), this is considered as a late-checkout.
- Otherwise (on or after 6PM), it's considered as a new day.

### Steps to Reproduce:
1. Set time to 3:59AM on the Room Management Screen
2. Create a same day booking (Sept 13, 2021 - Sept 13, 2021)

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133018654-0533f993-0fa6-431e-aee2-41ec4c77e440.png)

### Expected Results:
- The end date should be accepted

### Actual Results:
- An error message appeared

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
The check in follows the system time as it may be incorrect to use the chosen time in the room management screen in order to bypass the check in time of 4am. The chosen time in the room management screen is only present to be able to view the vacant/booked/occupied rooms for different times of the day.

**Comment by sophia-vista** [comment]
Noted! So same-day bookings are implemented yet cannot be tested as of now?

**Comment by JanjanC** [comment]
Ah dapat before 4am talaga system time.

**Comment by sophia-vista** [comment]
Okok will close this for now!
