### ISSUE TITLE
Fields for cash and percents should accept floating point numbers

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#118]
### Summary:
In transaction fields, floating-point numbers should be allowed in case of discounts with decimals or payments with centavos

### Current Design:
![image](https://user-images.githubusercontent.com/75743382/133058357-1d98c414-0d75-4d67-90fa-4b8adbe4000d.png)

### Suggested Design:
- 4000.00 should be accepted

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Updated

**Comment by sophia-vista** [comment]
![image](https://user-images.githubusercontent.com/75743382/133413517-43a96124-1325-4b14-b2b6-3e7285609c1f.png)
![image](https://user-images.githubusercontent.com/75743382/133414423-b33bcfc8-1cd7-4120-b4bb-576f2c92244d.png)

The decimal value does not reflect in the total discount
