### ISSUE TITLE
Clarify create check-in subheaders

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#120]
### Summary:
Refer to Issue #86, but for the check-in forms

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133067517-df501a8b-fc69-47c5-ba3e-6540674789dd.png)

### Suggested Changes:
Add "Create New Check-In" subheader

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ThisIsGrass** [comment]
Hello issue fixed!
