### ISSUE TITLE
Check-out information is not visible in confirm prompt

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#121]
### Summary:
The confirm prompt says, "Are you sure you want to check-out the booked guest with the following information?", yet there is no information present

### Steps to Reproduce:
- Check-out any occupied room

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133068049-6a9d461d-63b2-48f5-8373-fc7d4d5254e6.png)

### Expected Results:
- Information about the booked guest would be shown

### Actual Results:
- No information is seen

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ThisIsGrass** [comment]
Hello! My apologies for the poor wording. The information was supposed to pertain to the ones listed in the room card itself. Will probably be rewording the dialog prompt instead. Thank you!

**Comment by francheska-vicente** [comment]
wait

**Comment by francheska-vicente** [comment]
Hi! I think it would be better if the information is shown in the prompt itself? 

Additionally, the breakdown for extra charges should also be shown (early check-in, late check-out, extra person, and other extra charges).

**Comment by ThisIsGrass** [comment]
Hello! Willing to contest the idea of the information being shown in the additional dialog if possible. The reason being, the room info being shown again would be sort of redundant. The room card info already shows everything about it. Attempting to add information in the prompt would more or less look like having a repeat of the room card being prompted.

**Comment by JanjanC** [comment]
This is an hbs issue :(

**Comment by francheska-vicente** [comment]
In the scenario that the guest opts for late check-out, it would not be shown in the current room card. 

Thus, the solution that I thougt for this one was to either: (1) have a prompt showing all the extra charges, or (2) redirect to a form that has the transaction details. For (2), the "late check-out fee" is automatically put into the extra charges field and the employee has the power to add/modify the transaction details.

**Comment by sophia-vista** [comment]
> (2) redirect to a form that has the transaction details.

Implemented.
