### ISSUE TITLE
Transfer Room function should be separate from Edit Check-In function

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#122]
### Summary:
Transfer Room function should be treated as a separate function from modifying the information of a checked-in guest; instead of redirecting to the edit form, it should have a separate modal solely for transferring rooms

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133072257-9bceaa01-e9dc-4160-9ea0-66499879dcf8.png)

### Expected Results:
- Transfer button next to Edit button that shows a modal with a list of rooms to transfer to

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Reimplemented
