### ISSUE TITLE
Transaction details should be shown after pressing the checkout button

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#123]
### Summary
- After pressing the checkout button, the page should redirect to the transaction details of the guest which can be edited in order so that the user can still add additional charges as well as get a summary of the guest details. 
- The option to print should also be included here.

### Actual Results:
- Pressing the checkout button will immediately remove the guest.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
I believe this issue has been resolved?
