### ISSUE TITLE
Early check-in fee is not calculated when checking-in before 2pm

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#124]
### Summary
- Early check-in fee is not applied when checking-in before 2pm

### Steps to Reproduce
- Check in Room 302 at 11am (before 2pm)

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/133363253-8c9b7d62-060a-4dbd-b677-14bfef60e1b2.png)

### Expected Results:
- Total Extra charges would be P330 (5% of P2200 [Twin Bed] * 3 [from 11 to 2pm])
- Total cost should be P2530

### Actual Results:
- Extra charges are at 0
- Total cost is at P2200

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by Zet-Warden** [comment]
Applies to all User Stories with Check-In functionality

**Comment by JanjanC** [comment]
To clarify lang, is the early check-in time from 4am to 2pm?

**Comment by Zet-Warden** [comment]
- 4am to 1:59pm
- Also, early check-in is based on the daily rate, regardless if weekly or monthly yung type of accommodation.

**Comment by JanjanC** [comment]
Added computation for early checkin
