### ISSUE TITLE
When chosen time text field is blank, Javascript error occurs

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#127]
### Summary:
As the Chosen Time text field in Main Booking Screen and Room Management Screen allows inputs, it is possible to delete the text inside. This results in a Javascript error, causing the app to malfunction.

### Steps to Reproduce:
1. Go to Room Management or any Main Booking Screen
2. Delete text in Chosen Time field

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133723012-bfd8d537-5a0a-4de4-8a17-6925d1041238.png)

### Expected Results:
- Text cannot be deleted

### Actual Results:
- Javascript error

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed

**Comment by sophia-vista** [comment]
![image](https://user-images.githubusercontent.com/75743382/133868242-f93f4016-2216-4d79-8c64-a4492c14b069.png)
0 in the hour field still causes a Javascript error

**Comment by JanjanC** [comment]
I can't seem to find a way to prevent a time of 00:00 from being entered. Instead, the keyboard input is restricted and the user is required to use the time picker option to choose a time.
![image](https://user-images.githubusercontent.com/69952255/133873452-750565f6-62c8-42d1-8385-468352d8e098.png)
