### ISSUE TITLE
Deleting a booking in Room Management redirects to Booking 

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#128]
### Summary:
- Deleting a booking in the Room Management Page should redirect to Room Management Page instead of Booking Page

### Steps to Reproduce:
- Delete any booking in the Room Management Page

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133728018-aa4f648f-ab74-4097-b1f3-a3880e630834.png)

### Expected Results:
- User is redirected to Room Management Page

### Actual Results:
- User is redirected to Booking Page

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Updated
