### ISSUE TITLE
JavaScript error occurs when pressing the transfer button

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#130]
### Summary
- JavaScript error occurs when pressing the transfer button

### Steps to Reproduce
- transfer a checked-in room

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/133754955-19a9ef6f-dd64-446a-9224-8db1f915fa18.png)

### Expected Results:
- the page should be redirected to the transfer page

### Actual Results:
- client side crashes and becomes unresponsive

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
This issue related to Issue #122 since the transfer room function is currently being reimplemented after making the transfer room a separate page

**Comment by JanjanC** [comment]
Reimplemented
