### ISSUE TITLE
Details of room transferred to is not visible in confirm prompt

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#132]
### Summary:
When transferring rooms, the confirm prompt does not show the room type and number of the new room.

### Steps to Reproduce:
1. Create a check-in
2. Transfer to different room

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133868960-5bae1dc9-c3be-423e-b771-adabce6ff52f.png)

### Expected Results:
- Details about the new room would be seen

### Actual Results:
- Only details about the old room is seen

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ThisIsGrass** [comment]
Hello! The loading of values for the modal confirm prompt is a task that's done by devs.

**Comment by JanjanC** [comment]
Ayaw

**Comment by JanjanC** [comment]
Fixed
