### ISSUE TITLE
Change wording of room's status

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#133]
### Summary:
For consistency, it might be better if the wording of room's status is more understandable.

### Current Design:
![image](https://user-images.githubusercontent.com/75743382/133869608-d3181025-0c6e-432e-946c-2e07ab569836.png)

### Suggested Design:
Rooms in need of maintenance or cleaning: Required
Rooms in need of maintenance or cleaning: Not Required

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ThisIsGrass** [comment]
Hello! Issue has been fixed. Thank you!
