### ISSUE TITLE
Guest name is displayed as FIRSTNAME LASTNAME in Transfer Page

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#134]
### Summary:
- Placeholder for Guest Name was not updated; it shows FIRSTNAME LASTNAME

### Steps to Reproduce:
1. Create a booking
2. Transfer booking to a different room

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133872084-1ef65102-a27b-4f40-88f6-dc924f9409d5.png)

### Expected Results:
- Guest name would appear

### Actual Results:
- FIRSTNAME LASTNAME appeared

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed

**Comment by Zet-Warden** [comment]
Sariling issue, sariling fixed
