### ISSUE TITLE
Extra charges for number of beds should be hardcoded

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#135]
### Summary:
Charges for each extra bed is fixed at P400. Instead of an input, it can be automatically computed by the system.

### Current Design:
![image](https://user-images.githubusercontent.com/75743382/133916013-be0761cc-ef62-4522-b096-ba277825f121.png)

### Suggested Design:
- Total charges for extra number of beds should be automatically computed, input should be restricted on the field with computations.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Implemented
