### ISSUE TITLE
Extra pax charges value incorrect when changing the number of pax

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#136]
### Summary:
- If the number of pax was changed from having extra pax to having no extra pax, the Extra Pax Charges field does not update. 

For example:
Studio Type with Balcony (Max 2 pax w/o extra charges): If number of pax was changed from 5 to 2, there will still be 3 extra pax in the field; However, changing the value to 4 shows 2 extra pax.

### Steps to Reproduce:
1. Create a booking for Room 301
2. Input valid end date
3. Enter Number of Pax as 5
4. Change to 2

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133916159-34aedde2-b62f-4603-bb7b-ae0f810424e8.png)

### Expected Results:
Extra charges field would show 0 Number of Pax and 0 Extra Pax Charges

### Actual Results:
Extra charges field would show 3 Number of Pax and 1200 Extra Pax Charges

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by francheska-vicente** [comment]
Fixed
