### ISSUE TITLE
Other Charges input accepts 0 and negative values

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#137]
### Summary:
Other Charges fields should only accept positive float values.

### Steps to Reproduce:
1. Create a booking
2. Enter 0 in Other Charges field
3. Enter -150 in Other Charges field

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133916533-732fcc05-4d8d-4ea3-a78e-4776b046e6c1.png)

### Expected Results:
- An error message should appear

### Actual Results:
- Inputs are accepted as valid

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
