### ISSUE TITLE
Destination room type and number does not update after clicking on dropdown item

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#139]
### Summary:
Upon clicking on a room in the dropdown list, nothing happens

### Steps to Reproduce:
1. Transfer a currently occupied room
2. Click on any vacant room in the dropdown menu

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/133917376-0ad7ee8b-2159-4f05-836e-f5200dec5b78.png)

### Expected Results:
- Destination room type and number will update

### Actual Results:
- Destination room type and number does not update

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by francheska-vicente** [comment]
Fixed
