### ISSUE TITLE
No print button on room card

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#140]
### Summary
- Add print button to room card

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/133921429-611ce4d5-f6a6-478d-87d2-de057967236e.png)

### Suggested Results:
- print button should be available on the room card

### Actual Results:
- there is no print button on the room card

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed
