### ISSUE TITLE
Inputting invalid date for Dates returns an "Empty Date" error message

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#19]
### Summary:
- By typing the start date/end date/birthday manually, it is possible to input dates like November 31, 2021 (value for days do not exceed 31, but a value of 31 can still be inputted with months w/o 31 days). While the system does not accept the input, the error message is not applicable.

### Steps to Reproduce:
1. Log in
2. Click on Reservation
3. Click on Create Reservation
4. Manually type 11/31/2022 on the Start Date
5. Click on Confirm

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/130022085-cca6cb1b-3287-4711-b567-5939e7331703.png)

### Expected Results:
- Error message displays with an error message stating "Invalid date"

### Actual Results:
- Error message displays with an error message stating "Empty date"

| Additional Information | |
| ----------- | ----------- |
| Defect ID | 15-0015 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
