### ISSUE TITLE
Confirm button in Modify Reservation prompt does not redirect to the Main Reservation page

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#21]
### Summary:
- After clicking the Confirm button (in the confirm prompt when modifying a reservation), the user is redirected to the index page.

### Steps to Reproduce:
1. Log in
2. Click on Calendar
3. Click on the date today
4. Click on a reservation
5. Click Edit
5. Enter valid inputs
6. Click Modify
7. Click Confirm

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/130043774-f781f1e8-effa-48cf-a44c-8583b2ee24bf.png)

### Expected Results:
- The Main Reservation Page (of the date picked) is shown

### Actual Results:
- The Index Page is shown

| Additional Information | |
| ----------- | ----------- |
| Defect ID | 11-0001 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
