### ISSUE TITLE
Contact number field accepts symbols as input

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#27]
### Summary:
Contact number field of create registration is able to accept 'e' and '-' an input. 'e' gets flagged by validation but '-' does not.

### Steps to Reproduce:
1. Create a reservation
2. Input 'e' or '-' in the Contact number field 

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/130231504-0ae17173-2e6e-4f82-96c0-4ba6d4d89bdd.png)

### Expected Results:
Only digits can be inputted in the Contact number field

### Actual Results:
'e' and '-' gets accepted in the Contact number field

| Additional Information | |
| ----------- | ----------- |
| Defect ID | 15-0022 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
