### ISSUE TITLE
Whitespace chars accepted in optional information field

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#29]
### Summary:
Whitespaces are accepted in the optional information field for address, company, and occupation.

### Steps to Reproduce:
1. login
2. Calendar
3. Create a reservation
4. Input whitespace/s in the optional info field that accepts characters

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/130234633-412257ef-d273-4131-9588-6fdd196f38b4.png)

### Expected Results:
Information that are entirely whitespaces should be treated as if no information were entered.

### Actual Results:
Information inputted consisting of only whitespace are accepted.

| Additional Information | |
| ----------- | ----------- |
| Defect ID | 15-0024 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
