### ISSUE TITLE
Unable to book

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#39]
### Summary:
A javascript error is presenting itself when the book button has been clicked

### Steps to Reproduce:
1. login
2. go to booking
3. pick any vacant room
4. input valid information
5. press book

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/130771186-2192e838-ccb6-459f-8435-38a3eac7c8a0.png)

### Expected Results:
The booking should be saved.

### Actual Results:
A javascript error occurs.

| Additional Information | |
| ----------- | ----------- |
| Defect ID | 01-0001 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Issue caused by hbs changes of the Designer

**Comment by ThisIsGrass** [comment]
Issue fixed: reverted disabled attribute of muted fields. Instead, replaced with hover property behavior over muted fields.
