### ISSUE TITLE
Navigation disappears in booking form

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#40]
### Summary:
Navigation bar disappears after scrolling down in Booking form

### Steps to Reproduce:
1. login
2. go to booking
3. pick any room
4. scroll down to transactions

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/130772012-f31aa674-f566-4bbd-b8f8-99972dcfbab6.png)

![image](https://user-images.githubusercontent.com/74450482/130771751-ccb9ecb4-99f7-4c8c-8d12-44187aef6b3f.png)

### Expected Results:
Navigation bar should remain at the top of the page, which is the expected behavior as the navbar still remains when scrolling down UNTIL it reaches a certain part of the page.

### Actual Results:
Navigation bar disappears once it reaches a certain part of the page

| Additional Information | |
| ----------- | ----------- |
| Defect ID | 01-0002 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ThisIsGrass** [comment]
Fixed issue by editing css that prevents the nav from disappearing after reaching a certain amount of height in the page
