### ISSUE TITLE
Screen indicator not immediately visible when there is invalid input in field

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#44]
### Summary:
When booking a room with invalid information in the fields, the page stay as is without any indicator that there is an incorrect input in one of the fields. It seems that the app did nothing after booking or that the booking is successful.

### Steps to Reproduce:
1. login
2. go to booking
3. fill at least one field with invalid input
4. notice that there is no indicator that the user did something wrong

### Suggested Results:
Make the screen jump to the section where the user made an invalid input

### Actual Results:
The app does not provide any indicators to the user that they made an invalid input

| Additional Information | |
| ----------- | ----------- |
| Defect ID | 01-0006 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ilearnonthisaccount** [comment]
There are error messages indicating the invalid fields but they are validated in the back end so it only appears after you press book.
![image](https://user-images.githubusercontent.com/80669825/131298240-06eb0318-24e1-430e-8668-c8359d511a9e.png)
![image](https://user-images.githubusercontent.com/80669825/131298261-7049b922-8108-4ef2-bc68-78587d14970a.png)

**Comment by Zet-Warden** [comment]
regarding this, ibig sabihin pala nito is pag kunwari
may error sa firstname lang (which is nasa taas ng screen), di siya kita agad pag nag create ng booking
so bale need lang for here is magredirect siya sa taas ng page maybe

Sorry for the confusion, changed the title

**Comment by ilearnonthisaccount** [comment]
added scroll animation after failing validation

**Comment by Zet-Warden** [comment]
The screen scrolls to the room details/customer details even if information there is valid. For clarification, the screen should scroll to areas where there are invalid information.

**Comment by ilearnonthisaccount** [comment]
updated it

**Comment by Zet-Warden** [comment]
scrolling does not happen when contact number is invalid

**Comment by ilearnonthisaccount** [comment]
updated to account for contact number

**Comment by sophia-vista** [comment]
> updated to account for contact number

Does not reflect pa rin HUHU, did you push ba pala @ilearnonthisaccount

**Comment by ilearnonthisaccount** [comment]
woops hanggang commit lang pala nagawa ko my bad
