### ISSUE TITLE
Excess charges for number of guests not reflecting on total cost

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#56]
### Summary:
- There are additional charges for when the number of guests exceeds the limit of guests for a specific room. For each excess guest, a flat rate of P400 pesos per day is charged.

### Steps to Reproduce:
1. Create a booking for September 1, 2021 - September 10, 2021 in Room 302
2. Set number of guests as 10

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131079698-26f0eacb-15d0-4080-9614-f7489cc33c21.png)

### Expected Results:
- Total Cost should be 46800.00

### Actual Results:
- Total Cost is only 18400.00

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by francheska-vicente** [comment]
Additionally, the computation for the room cost for >= 7 and < 30 is incorrect. It should be weekly_room_rate / 7 * #_of_days. 

@JanjanC @ilearnonthisaccount

**Comment by JanjanC** [comment]
Updated
