### ISSUE TITLE
Ongoing bookings should be editable

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#57]
### Summary:
- Bookings that are ongoing cannot be edited due to an error with the start date validation.

### Steps to Reproduce:
1. Click on a booking that is ongoing (start date in the past, end date in the future)
2. Edit any field
3. Confirm the booking

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131084487-01099d69-91b8-407d-bf81-0dbe963f8bd8.png)

### Expected Results:
- The booking would successfully be edited.

### Actual Results:
- An error message appears on the start date field stating that the Start Date cannot be earlier than Today.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
