### ISSUE TITLE
Top navigation bar creates a second row

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#6]
### Summary:
The top navigation bar on has 2 rows for screen resolution - 1920x1080; screen size - 15 inches.
### Steps to Reproduce:
1. Login
2. Go to Calendar
3. (For different screen resolution and size from summary, dev tools has a responsive section)
### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/129738604-94305324-f18a-4559-894d-ae4dbc5baa79.png)

### Expected Results:
There should only be one row for the navigation bar.
### Actual Results:
There are two rows for the navigation bar.
| Additional Information | |
| ----------- | ----------- |
| Defect ID | 15-0004 |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by sophia-vista** [comment]
Issue not visible on monitor with screen resolution - 1920x1080; screen size - 22 inches.
