### ISSUE TITLE
Validate mobile number input

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#62]
### Summary:
- In creating a reservation, if the User opts to fill in the contact information field, the number should be a valid PH number. A valid PH number would be a mobile number that starts with 09, and is exactly 11 digits long (including the 09). An error message should appear if the information does not conform to the format, reservation would also not push through if the information does not conform to the format. 

### Steps to Reproduce:
1. login
2. go to reservation
3. create a reservation
4. fill with valid information
5. input invalid mobile number in the Contact Information field

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/131107611-df546163-ac7d-4c82-ae0f-a8f60614bbc4.png)
![image](https://user-images.githubusercontent.com/74450482/131107644-17258bb1-471a-4d40-8f9e-189d5bfae80b.png)

### Expected Results:
- Error message should appear when mobile number is not in the correct format. Reservation should not push through.

### Actual Results:
- The application does not validate the mobile number field. The reservation pushes through.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by Zet-Warden** [comment]
The reservation still gets created

**Comment by JanjanC** [comment]
Fixed under the US-15 branch. The length of the phone number has also been limited to 11.
