### ISSUE TITLE
Username is not reflected in the navbar.

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#66]
### Summary:
Username is not reflected in the navbar.

### Steps to Reproduce:
1. login

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/131295662-a2134232-3162-4e20-ae04-518cfc13a67e.png)

### Expected Results:
Username from login appears in the navbar

### Actual Results:
The name "username" appears.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Added usernames
