### ISSUE TITLE
Invalid birthdate error message does not appear

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#67]
### Summary:
- Inputting an invalid birthdate (e.g. date is after today) would not show an error message in the Edit Reservation Screen, though the reservation will not push through.

### Steps to Reproduce:
1. Create a reservation
2. Enter Oct. 01, 2021 as the birthdate
3. Click on Edit 

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131296875-fc44a3fa-dc58-4bb9-8057-53792efa78db.png)

### Expected Results:
- Error Message will appear saying "Invalid birthdate"

### Actual Results:
- Reservation does not push through but there is no error message

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Added error fields
