### ISSUE TITLE
Change placeholder for Contact Number

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#70]
### Summary:
- Error message for invalid contact number needs more information. To circumvent this, placeholder of the contact number field should provide a hint for the format of the contact number.

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/131299514-f6be9317-ef84-4c26-aede-228061244b81.png)

### Suggested Placeholder
- (Optional) Enter Mobile Number 09XXXXXXXXX

### Actual Placeholder:
- (Optional) Enter Contact Number

### Notes:
- Mobile Number instead of Contact Number as reference to issue #71 

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed!!
