### ISSUE TITLE
Change contact no to mobile no

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#71]
### Summary:
- The field of contact no. can have many interpretations such as telephone no, and email. In order to be more specific, change the field name to mobile no.

### Steps to Reproduce:
1. login
2. click on any date
3. create reservation

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/131299842-8689da39-2ad4-40ab-bdc0-87c2946542d5.png)

### Expected Results:
- Mobile no. should be the name of the field instead of contact no.

### Actual Results:
- Contact no. is the name of the field.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed!!
