### ISSUE TITLE
Total cost not appearing if PWD and Senior Citizen fields were not filled

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#72]
### Summary:
After inputting all required information, the total cost does not appear.

### Steps to Reproduce:
1. Create a booking with valid required inputs

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131304641-07e6cb75-5c41-410b-831a-bebf7e5ec1c8.png)
![image](https://user-images.githubusercontent.com/75743382/131304686-c16b101b-396c-4b69-a781-dd9c2a413285.png)

### Expected Results:
- Total cost should appear after inputting the required information

### Actual Results:
- Total cost only appears if PWD and Senior Citizen fields were filled

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Currently unable to reproduce this issue

![image](https://user-images.githubusercontent.com/69952255/131310527-1a06cb3a-2e7e-4e24-8b01-3648505b446f.png)
![image](https://user-images.githubusercontent.com/69952255/131310868-b5e743d9-2ca6-4f1d-b92b-ea78ba3aba5b.png)

**Comment by Zet-Warden** [comment]
Same issue for me sa US#18
![image](https://user-images.githubusercontent.com/74450482/131311594-f2f15407-8e74-4032-835b-7cee7c99d445.png)
![image](https://user-images.githubusercontent.com/74450482/131311640-0a6614f1-d50b-4032-b77f-f70c8699f911.png)

**Comment by JanjanC** [comment]
Fixed, this issue might have been caused by an incorrect merge.
