### ISSUE TITLE
Error messages do not disappear after reservation is deselected

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#73]
### Summary:
When picking a reservation with invalid inputs, deselecting this reservation does not remove any error messages that appeared.

### Steps to Reproduce:
1. Go to create a booking page. (August 30, 2021 - Room 888)
2. Pick reservation "test test" from the dropdown menu
3. Remove reservation in the dropdown menu.

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131304967-e1b8a65c-00a9-400b-a8e6-3ce6d176753e.png)

### Expected Results:
- Error messages would be reset

### Actual Results:
- Error messages stayed

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
