### ISSUE TITLE
Monthly price not changing depending on pax

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#75]
### Summary:
- Studio type monthly price does not change depending on pax

### Steps to Reproduce:
1. login
2. pick any date
3. create booking
4. set a date so that the number of days is at 30 days
5. change the number of pax to 2

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/131309324-901586df-f597-4461-839c-f62e08abffe5.png)

### Expected Results:
- The total price should be Php 28,800 for 2 pax on studio type monthly

### Actual Results:
- The total price is Php26,400 which is reflected for 1pax on studio type monthly

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed. This issue was caused by an incorrect encoding of data in the database.
