### ISSUE TITLE
User should be able to enter discounts for both pwd/senior and other discounts

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#76]
### Summary:
- Pwd/senior gets removed when adding discount for 'other discounts' and vice versa.
- User should be able to enter discounts for both pwd/senior and other discounts. The bigger of the two is the only discount to be honored.

### Steps to Reproduce:
1. login
2. pick any date
3. create booking
4. type 2 in number of pwd
5. select a field under 'other discounts'

### Expected Results:
- User should be able to add information for both pwd/senior and other discounts field. The bigger of the two will be honored.

### Actual Results:
- User can only choose to add discount to one of the fields at a time

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Reimplemented.
