### ISSUE TITLE
Combined rooms should be dependent on both room's availability

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#77]
### Summary:
Some rooms are combinations of two other rooms:
- Room 302&303 is the combination of Room 302 and 303
- Room 888 is also Room 302&303 but for special events
- Room 304&305 is the combination of Room 304 and 305
- Room 999 is also Room 304&305 but for special events

The availability of these rooms should be dependent on each other. Therefore:
- When 302 or 303 is booked, 302&303 and 888 should be unavailable.
- When 302&303 is booked, 302, 303, and 888 should be unavailable.
- When 888 is booked, 302, 303, and 302&303 should be unavailable.
- When 304 or 305 is booked, 304&305 and 999 should be unavailable.
- When 304&305 is booked, 304, 305, and 999 should be unavailable.
- When 999 is booked, 304, 305, and 304&305 should be unavailable.

### Steps to Reproduce:
1. Create a booking in Room 302
2. Check the Room Array

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131314837-63930cd4-43f0-45f6-aa64-f961d45116ab.png)

### Expected Results:
- 302&303 and 888 should be unavailable.

### Actual Results:
- 302&303 and 888 is still available.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ilearnonthisaccount** [comment]
Have made changes, please check.

**Comment by sophia-vista** [comment]
Opened again, these rooms being unavailable should mean that either the room button in the room array is disabled, or a separate category is defined for unavailable rooms

ex. if 303 is booked, 302/303 and 888 should be unavailable (room card is not shown when clicked)

**Comment by sophia-vista** [comment]
Update: This should also be implemented in the Check-in Screen

**Comment by JanjanC** [comment]
@ilearnonthisaccount

**Comment by JanjanC** [comment]
Disabled the create booking button for rooms that are unavailable (i.e., the connected rooms are either booked or occupied). 
In addition, should the color of the room tile of an unavailable room be the same as a vacant room or a booked/occupied room.

**Comment by sophia-vista** [comment]
Better ata if different color na lang to avoid confusion, @francheska-vicente wdyt

**Comment by francheska-vicente** [comment]
I think it would be better if mayroong new color/category. 

It maybe a bit confusing if for example, the guest only booked room 302 pero mapapakita na booked din yung 302&303. Pwedeng maging confusing kay user kung ano sa rooms na 'yun yung talagang para kay guest.

**Comment by JanjanC** [comment]
@ThisIsGrass , paimplement nalang ng new color

**Comment by ThisIsGrass** [comment]
Added new color and legend for unavailable
