### ISSUE TITLE
Confirm reservation/booking prompts can be organized by information type

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#81]
### Summary:
Information in the confirm prompts can follow the format used in the Room Cards

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131790560-603a2f76-234a-4ac2-a36d-b89c0122c58d.png)

### Suggested Results:
![image](https://user-images.githubusercontent.com/75743382/131790693-1a1ddcca-434a-4207-bb59-ea301f67de03.png)
(Something similar to this)

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by ilearnonthisaccount** [comment]
Update has been pushed to support this.

**Comment by sophia-vista** [comment]
Transaction details are missing

**Comment by ilearnonthisaccount** [comment]
There are no transaction details for reservations?

**Comment by sophia-vista** [comment]
Ah for bookings rin to HAHAHA

**Comment by ilearnonthisaccount** [comment]
Updated na rin for bookings
