### ISSUE TITLE
Cancelled reservation should redirect to cancelled reservation's start date 

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#82]
### Summary:
Deleting a reservation on a future date would redirect the user to the current date instead of the reservation's start date

### Steps to Reproduce:
1. Create a reservation that would start on a future date
2. Delete the reservation

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131791148-6b013ebe-6f4a-4222-a300-1fca5ea3881a.png)
(Redirected to Sept. 2 instead of Sept. 16)

### Expected Results:
- Redirected to Sept 16 Main Reservation Page

### Actual Results:
- Redirected to Sept 2 Main Reservation Page

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
