### ISSUE TITLE
PWD discount remains even after unchecking the field

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#84]
### Summary
- Discount remains even though the discount field for PWD is unchecked

### Steps to Reproduce
1. login
2. go to booking
3. pick room 301
4. make the end date be exactly 30 days from start date
5. input 2 for the number of pax
6. input 1 for number of pwd
7. uncheck the pwd field

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/131974256-bc0b5560-bb40-4bf6-ac7b-b6a2520bd5ec.png)

### Expected Results:
- discount should be zero since the field has been unchecked and the previous input has been cleared

### Actual Results:
- previous discount remains

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by sophia-vista** [comment]
Update: all discounts have this issue

**Comment by JanjanC** [comment]
Fixed
