### ISSUE TITLE
Reservation appears whose range does not include the chosen date of booking

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#85]
### Summary
- Reservation appears whose range does not include the chosen date of booking.

### Steps to Reproduce
- login
- choose September 3 as the date of booking 
- click on select a reservation drop down

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/131975985-dc25d74c-c0d1-4bcf-b648-0a45441c2b37.png)

### Expected Results:
- Reservation whose range does not include the chosen date of booking should not appear in the list.

### Actual Results:
- Reservation whose range does not include the chosen date of booking appears in the list.

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
John A. Doe | Aug 24 2021 - Aug 26 2021 is only a placeholder. The feature of converting a reservation into a booking is implemented in US18 (not US1)

**Comment by sophia-vista** [comment]
@Zet-Warden nako jacob

**Comment by Zet-Warden** [comment]
ay oops wrong US# pala ako mbmb
