### ISSUE TITLE
Rooms that offer monthly rate should not have extra persons for monthly accommodation

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#87]
### Summary
- Rooms that offer monthly rates should not entertain extra pax when the guest/s is opts for a monthly stay.

### Steps to Reproduce
1. login
2. choose any date for booking
3. choose room 305
4. input 100 in the number of pax field

### Visual Proof
![image](https://user-images.githubusercontent.com/74450482/131984778-e9ee807c-8b8d-497a-a225-61de857b3af3.png)

### Expected Results:
- Number of persons should be limited to at most 4 pax for twin bed (rm. 305).

### Actual Results:
- There is no limit to the number of extra pax for the monthly rate of twin bed (rm. 305).

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed

**Comment by sophia-vista** [comment]
![image](https://user-images.githubusercontent.com/75743382/132183727-d7e27915-9b2f-4726-a698-ffa28546f01c.png)
![image](https://user-images.githubusercontent.com/75743382/132183789-c01ef84b-b1be-4f6e-9f45-dc78e2ccc9ec.png)
![image](https://user-images.githubusercontent.com/75743382/132183816-123cf8a2-13c1-4398-a0bd-7413b42299de.png)
![image](https://user-images.githubusercontent.com/75743382/132183866-7a58d816-de3a-47fc-8afd-5754058734dc.png)

Error message appears but booking pushes through

**Comment by JanjanC** [comment]
Oops, fixed.
