### ISSUE TITLE
Reservation that was booked should be removed from the reservation list

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#88]
### Summary:
- After booking a reservation, it should be removed from the reservation list.

### Steps to Reproduce:
1. Create a Booking from a Reservation
2. Go to the Main Reservation page

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131985958-f114a503-6003-4a07-b6e6-ce7703310738.png)

### Expected Results:
- Reservation is removed from the list of reservations

### Actual Results:
- Reservation is still there

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
This issue cannot be reproduced. The reservation is removed from the reservation list after converting a reservation into a booking.
![image](https://user-images.githubusercontent.com/69952255/132094595-3e4af57e-cdb8-4e56-9fa8-d82da4a9fa4e.png)
![image](https://user-images.githubusercontent.com/69952255/132094612-e83f1be1-f2df-4a95-a8cb-0c6c6f0f9c8b.png)
![image](https://user-images.githubusercontent.com/69952255/132094619-e8cfe628-4bbe-4d03-9c2e-4375e342d4ba.png)
![image](https://user-images.githubusercontent.com/69952255/132094634-4364c4ef-9b16-4bdc-82c2-2310a0208998.png)

**Comment by sophia-vista** [comment]
hehe sorry
