### ISSUE TITLE
Delete booking function does not work

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#89]
### Summary:
- The function to delete bookings does not work, it redirects to an error page

### Steps to Reproduce:
1. Delete a booking

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131987578-fe4b4820-0511-4bcf-b976-90bb946ad9df.png)
![image](https://user-images.githubusercontent.com/75743382/131987627-348dd36c-cd7a-4543-9c24-3e474c2334a0.png)

### Expected Results:
- Booking would be successfully deleted

### Actual Results:
- Error page is shown

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed. There was an error with the action attribute of the form.
