### ISSUE TITLE
Variable assignment that was never used

### ISSUE THREAD

**Issue by Zet-Warden** [francheska-vicente/cssweng#9]
### Summary:
Assigning of variable that has not never been used

### Where:
- help.js: ln 3, ln 8

### Visual Proof:
![image](https://user-images.githubusercontent.com/74450482/129744411-b8d85760-a48a-4cb3-bb04-585f4c175bc3.png)

### Expected Coding Format:
No unnecessary assignment of variable.

### Actual Coding Format:
Trivial assignment of variable

| Additional Information | |
| ----------- | ----------- |
| Defect ID |  15-0008|

**Comment by sophia-vista** [comment]
Issue closed - variable still essential to tooltips
