### ISSUE TITLE
Mobile Number error message does not appear

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#90]
### Summary:
- Inputting an invalid mobile number (e.g. wrong format) would not show an error message in the Edit Booking Screen, though the booking will not push through.

### Steps to Reproduce:
1. Create a reservation
2. Enter 123 as the mobile number
3. Click on Edit

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131988852-84eb7d02-ad27-46aa-a368-28818a15c5a1.png)

### Expected Results:
- Error Message will appear saying "Invalid mobile number"

### Actual Results:
- Booking does not push through but there is no error message

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
