### ISSUE TITLE
Date fields are still editable

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#91]
### Summary:
- Date fields are editable, which could cause errors due to invalid dates

### Steps to Reproduce:
1. Modify a booking
2. Type in the start date field

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131989749-9b2eb2c2-084b-431e-b9de-4a532f04ab9f.png)

### Expected Results:
- Input will not be registered

### Actual Results:
- Input is still registered

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
FIxed
