### ISSUE TITLE
Transaction details are blank when modifying

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#92]
### Summary:
- Previously filled transaction details should reflect in their fields when editing a booking.

### Steps to Reproduce:
1. Edit an existing booking

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/131990216-c1ac1e30-7962-4e46-90fa-6a8e131a7f31.png)

### Expected Results:
- Transaction details should have information

### Actual Results:
- All transaction details are blank

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed

**Comment by sophia-vista** [comment]
Number of Guests and Customer Payment should also be reflected

**Comment by JanjanC** [comment]
Implemented new feature of saving the number of guests and customer payment to the database

**Comment by francheska-vicente** [comment]
Update: If the employee also entered some discounts and number of pwd/senior citizen, it should also be reflected when editing.
