### ISSUE TITLE
Extra pax for monthly rate of Studio Type with Balcony and Combined Room still pushes through

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#93]
### Summary
- Studio Type w/ Balcony counts as Studio Type, which has a maximum of 2 pax for monthly rates
- Combined Room has a maximum of 5 pax for monthly rates

### Steps to Reproduce:
- Create booking (Room 301, 3 pax, Jan 1 2021 - Jan 31 2021)
- Create booking (Room 302303, 6 pax, Jan 1 2021 - Jan 31 2021)

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/132225413-1b89f0b5-849b-49cc-ab3e-c76fb0213da8.png)

### Expected Results:
- Error message would appear

### Actual Results:
- Bookings pushed through

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Does this also mean that a Twin Bed w/ Balcony is also considered as a Twin Bed despite the daily and weekly rate being different? Or does this only apply for Studio Types?

**Comment by francheska-vicente** [comment]
Confirming with the client. Will update you once he replies!

**Comment by francheska-vicente** [comment]
Update: Yes, the twin bed with balcony also has the same **monthly** rate as the Twin Bed. Same with the Studio and Studio with Balcony.

**Comment by JanjanC** [comment]
Updated the database to reflect these changes.
