### ISSUE TITLE
Discounts do not reflect when booking for Bridal Family Room

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#94]
### Summary:
- Only for Bridal Family Room, when inputting discounts, the total cost does not change

### Steps to Reproduce:
- Create Booking (Room 999, Sept 8-10, 2 pax, 2 PWD, 2000PHP discount)

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/132449619-1a811adb-87dd-4527-bf7b-e8f6cc24dd51.png)
![image](https://user-images.githubusercontent.com/75743382/132449593-61501861-58b6-4f18-97c6-efd9dab4637b.png)

### Expected Results:
- Total cost would change

### Actual Results:
- Total cost remained the same

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed. This is a DB issue.
