### ISSUE TITLE
Total cost can be negative if discount is greater than initial cost

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#95]
### Summary:
- Discounts should not exceed the initial cost

### Steps to Reproduce:
- Create booking (Sept 9 - Sept 10, 100000PHP discount)

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/132450447-cedf3be5-6495-42cf-a5b9-d25beff0b6c6.png)

### Expected Results:
- Error message will appear

### Actual Results:
- Booking pushes through

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Fixed
