### ISSUE TITLE
Wrong computation for Twin Bed

### ISSUE THREAD

**Issue by sophia-vista** [francheska-vicente/cssweng#96]
### Summary:
Exceeding the max number of pax (max 2) does not add extra charge

### Steps to Reproduce:
- Create booking (Room 302, Oct 1 - Oct 9, 3 pax)

### Visual Proof:
![image](https://user-images.githubusercontent.com/75743382/132485147-6be23a99-8430-458a-afa0-d1191b823a12.png)

### Expected Results:
- Total cost is 16400

### Actual Results:
- Total cost is 16000

| Additional Information | |
| ----------- | ----------- |
| Platform | V8 engine (Google) |
| Operating System | Windows 10 |

**Comment by JanjanC** [comment]
Updated computation of discount
